from game import Game
from engine import Engine

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 500
BG_COLOR = (0, 0, 0)
PARTICLE_COLOR = (255, 255, 255)
FPS = 120

NUM_PARTICLES = 12
DIAG_ONE = (0, 0)
DIAG_TWO = (SCREEN_WIDTH, SCREEN_HEIGHT)
WALL_ELASTICITY = 1.0
PARTICLE_ELASTICITY = 1.0
ACCLN = (0, 0.000)

PARTICLE_MASS = 5.0
PARTICLE_RADIUS = 5.0
PARTICLE_MAX_VEL = (-0.5, 0.5)

T_COSNST = 0.25


def main():
    engine = Engine(NUM_PARTICLES, DIAG_ONE, DIAG_TWO, WALL_ELASTICITY, PARTICLE_ELASTICITY, ACCLN,
                    PARTICLE_MASS, PARTICLE_RADIUS, PARTICLE_MAX_VEL, T_COSNST)
    game = Game(SCREEN_WIDTH, SCREEN_HEIGHT, BG_COLOR, PARTICLE_COLOR, FPS)

    engine.create_particles()
    game.start(engine)


if __name__ == "__main__":
    main()
